spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bnkinner?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: bnk
    password: bnk
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
 #      show_sql: true
 #      format_sql: true
        
logging.level:
  org.hibernate.SQL: debug
  

